### ISSUE TITLE
Discuss, document and enforce version numbering routines

### ISSUE THREAD

**Issue by albbas** [giellalt/giella-shared#2]
When building the mobile speller for divvun.org, the compilation fails

./configure --without-forrest --enable-spellers --disable-hfst-desktop-spellers --prefix=$HOME/.local --enable-hfst-mobile-speller

/usr/bin/hfst-lexc: The file lexicon.tmp.lexc did not compile cleanly.

**Comment by albbas** [comment]
Setup version dependency á la giella-core. If it exists, use it actively to avoid unnecessary issues like this.

**Comment by Trondtr** [comment]
Eg ser at feilen er at eg hadde ei uinsjekka linje i giella-shared, slik at det ikkje vart oppdatert. Eg fiksar det no, og sannsynlegvis betyr det at eg skal sjekke inn leksikona på nytt.

**Comment by Trondtr** [comment]
No har eg oppdatert giella-shared (det var ei endring eg ikkje hadde sjekka inn som stoppa gut, så eg hadde ikkje siste verjson) og eg har kommentert inn att dei problematiske leksikona i mdf, mhr, myv. fst-ane kompilerer, no også med dei siste namna.

**Comment by snomos** [comment]
One question is whether it would be better to split this repository into multiple ones, one for each top level subdir. It will increase the number of dependencies for each language repository, but would restrict the dependencies to only the relevant parts.

**Comment by snomos** [comment]
> One question is whether it would be better to split this repository into multiple ones, one for each top level subdir. It will increase the number of dependencies for each language repository, but would restrict the dependencies to only the relevant parts.

Thinking more about this, I believe it is not a good idea. It will lead to dependency and thus maintenance hell.

There is already a version check mechanism in place. But it must be used and enforced. So what we need is a receipt for when and how to increase version numbers both here and in the dependent repositories.

**Comment by snomos** [comment]
> > One question is whether it would be better to split this repository into multiple ones, one for each top level subdir. It will increase the number of dependencies for each language repository, but would restrict the dependencies to only the relevant parts.
> 
> Thinking more about this, I believe it is not a good idea. It will lead to dependency and thus maintenance hell.

Thinking even more, and discussing with others, it was concluded that this was indeed a good idea. See giellalt/giella-core#20 .

I will close this issue now as resolved.
